#!/bin/sh

jq -n \
  --slurpfile g gemeinden_95_geo.json \
  --slurpfile m vorwahlen+plz.json '
  def key: ((.properties.iso // .properties.name) | tostring);

  ($m[0].features | reduce .[] as $f ({}; .[($f | key)] = $f)) as $mapped
  | $g[0].features[]
  | . as $gk
  | ($mapped[($gk | key)] // null) as $hit
  | {
      iso: $gk.properties.iso,
      name: $gk.properties.name,
      missing_plz: ($hit == null or (($hit.properties.plz? // {}) | length == 0)),
      missing_vorwahl: ($hit == null or (($hit.properties.vorwahl? // {}) | length == 0))
    }
  | select(.missing_plz or .missing_vorwahl)
'
